name: Create Windows executable
  # You may pin to the exact commit or the version.
  # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: .
    - uses: actions/uploadartifact@v2
      with:
        name: RdsLogReader
        path: dist/loggui
